/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (id INT GENERATED BY DEFAULT AS IDENTITY, name VARCHAR, date_of_birth DATE, escape_attempts INT, neutered BOOLEAN, weight_kg DECIMAL);

ALTER TABLE animals ADD species VARCHAR;

CREATE TABLE owners(id INT GENERATED BY DEFAULT AS IDENTITY, full_name VARCHAR, age INT, PRIMARY KEY (id));
CREATE TABLE species(id INT GENERATED BY DEFAULT AS IDENTITY, name VARCHAR, PRIMARY KEY(id));
ALTER TABLE animals ADD PRIMARY KEY (id);
ALTER TABLE animals DROP COLUMN species;
ALTER TABLE animals ADD species_id INT;
ALTER TABLE animals ADD FOREIGN KEY (species_id) REFERENCES species(id);
ALTER TABLE animals ADD owner_id INT;
ALTER TABLE animals ADD FOREIGN KEY (owner_id) REFERENCES owners(id);

CREATE TABLE vets(id INT GENERATED BY DEFAULT AS IDENTITY, name VARCHAR, age INT, date_of_graduation DATE, PRIMARY KEY (id));
CREATE TABLE specializations(vets_id INT REFERENCES vets(id), species_id INT REFERENCES species(id));
CREATE TABLE visits(animals_id INT REFERENCES animals(id), vets_id INT REFERENCES vets(id), date_of_visit DATE);

